# Generated by Django 5.1.2 on 2024-11-04 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(25), django.core.validators.MinLengthValidator(7)]),
        ),
    ]
