# Generated by Django 5.1.2 on 2024-11-04 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
