# Generated by Django 5.1.2 on 2024-11-06 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historytransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
