# Generated by Django 5.1.2 on 2024-11-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_historytransactions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryTransActions',
            new_name='TransActionsHistory',
        ),
    ]
